# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - name: subscription
    value: 'Visual Studio Enterprise' 
  - name: subscriptionId
    value: 'e66e44f5-c9bb-4501-9a65-6214bc0fd534' 
  - name: websiteName
    value: my-personal-website
  - name: location
    value: 'West Europe'
  - name: azureResourceManagerConnection
    value: 'Visual Studio Enterprise'
  - name: sku
    value: 'Basic'
  - name: skuCode
    value: 'B1'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  displayName: Build stage

  jobs:
    - job : Build 
      steps:
      - task: CopyFiles@2
        inputs:
          contents: | 
            'src/**'
            'pipeline/**'
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish build artifact
        inputs:
          artifactName: drop
    
    - job : Deploy 
      steps:
      # - task: DownloadBuildArtifacts@0
                 
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: $(azureResourceManagerConnection)
          subscriptionId: '$(subscriptionId)'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(websiteName)-rg'
          location: $(location)
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.ArtifactStagingDirectory)/pipeline/website-resources.json'
          overrideParameters: '
            -name $(websiteName) 
            -location $(location)
            -sku $(sku)
            -skuCode $(skuCode)'
          deploymentMode: 'Incremental'
