# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  - name: subscription
    value: 'Visual Studio Enterprise' 
  - name: resourceGroupName
    value: my-personal-website 
    
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job : build 
    steps:

    - script: echo first time!
      displayName: 'Starting'

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifact
      inputs:
        artifactName: drop

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: $(subscription)
        resourceGroupName: $(resourceGroupName)
        location: 'West Europe'
