# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


variables:
  - name: subscription
    value: 'e66e44f5-c9bb-4501-9a65-6214bc0fd534' 
  - name: resourceGroupName
    value: my-personal-website 
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo first time!
  displayName: 'Startingt'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(subscription)
    resourceGroupName: $(resourceGroupName)